version: '3.8'

name: fapstars-backend-dev

x-def-logging: &default-logging
  logging:
    driver: "loki"
    options:
      loki-url: "http://localhost:3100/loki/api/v1/push"
      loki-batch-size: "100"
      loki-retries: 2
      loki-max-backoff: 1000ms
      loki-timeout: 1s

services:
  nginx:
    <<: *default-logging
    container_name: nginx
    image: nginx:1.23.3
    volumes:
      - ./ci/nginx/:/etc/nginx/:ro
    ports:
      - "80:80"
      - "443:443"
  backend:
    <<: *default-logging
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '${PORT}:$PORT'
    env_file: .env
    depends_on:
      - db
      - redis-queue
      - redis-cache
    volumes:
      - ./:/var/www/app
      - /var/www/app/node_modules/

  db:
    <<: *default-logging
    image: postgres:16.3
    restart: always
    ports:
      - '${DB_PORT}:5432'
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - db-data:/var/lib/postgresql/data
  pgadmin:
    <<: *default-logging
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USER}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - 30131:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  db_test:
    <<: *default-logging
    image: postgres:16.3
    restart: always
    ports:
      - '${TEST_DB_PORT}:5432'
    environment:
      - POSTGRES_PASSWORD=${TEST_DB_PASSWORD}
      - POSTGRES_USER=${TEST_DB_USER}
      - POSTGRES_DB=${TEST_DB_DATABASE}

  redis-queue:
    <<: *default-logging
    image: redis:7.4
    container_name: redis_queue
    ports:
      - '${QUEUE_REDIS_PORT}:${QUEUE_REDIS_PORT}'
    volumes:
      - redis-queue-data:/data
    command: ['redis-server', '--appendonly', 'yes', '--requirepass', '$QUEUE_REDIS_PASSWORD', '--port', '$QUEUE_REDIS_PORT']

  redis-cache:
    <<: *default-logging
    image: redis:7.4
    container_name: redis_cache
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    volumes:
      - redis-cache-data:/data
    command: ['redis-server', '--appendonly', 'yes', '--requirepass', '$REDIS_PASSWORD', '--port', '$REDIS_PORT']

  redis-websocket-session:
    <<: *default-logging
    image: redis:7.4
    container_name: redis_websocket_session
    ports:
      - '${WEBSOCKET_SESSION_REDIS_PORT}:${WEBSOCKET_SESSION_REDIS_PORT}'
    volumes:
      - redis-websocket-session-data:/data
    command: [ 'redis-server', '--appendonly', 'yes', '--requirepass', '$WEBSOCKET_SESSION_REDIS_PASSWORD', '--port', '$WEBSOCKET_SESSION_REDIS_PORT' ]

volumes:
  redis-queue-data:
  redis-cache-data:
  redis-websocket-session-data:
  pgadmin-data:
  db-data:
