stages:
  - deploy

before_script:
  - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )"
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | base64 -d | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - echo "StrictHostKeyChecking no" > ~/.ssh/config

deploy_app:
  stage: deploy
  script:
    - ssh root@$REMOTE_HOST_IP "cd $DEPLOY_PATH && git pull origin main && docker compose -f docker-compose.prod.yml up -d --build"
