apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: rtht4efdgtyt5re43t5y
    access: proxy
    url: http://prometheus:9090
    basicAuth: true
    basicAuthUser: foo
    editable: true
    secureJsonData:
      basicAuthPassword: bar
  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    basicAuth: false
    version: 1
    editable: true
